/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

VectorPropertyWindow=function(){PropertyWindow.call(this);this.setDimension(180,150);};VectorPropertyWindow.prototype=new PropertyWindow;VectorPropertyWindow.prototype.type="VectorPropertyWindow";VectorPropertyWindow.prototype.createHTMLElement=function(){var item=PropertyWindow.prototype.createHTMLElement.call(this);this.lineColorLabel=this.createLabel("Line Color:",15,100);item.appendChild(this.lineColorLabel);this.fillColorLabel=this.createLabel("Fill Color:",15,120);item.appendChild(this.fillColorLabel);this.lineColorArea=this.createLabel("&nbsp;",85,100);this.lineColorArea.style.width="50px";this.lineColorArea.style.border="1px solid gray";this.lineColorArea.hostDialog=this;this.lineColorArea.onclick=function(){this.hostDialog.showLineColorDialog();};item.appendChild(this.lineColorArea);this.fillColorArea=this.createLabel("&nbsp;",85,120);this.fillColorArea.style.width="50px";this.fillColorArea.style.border="1px solid gray";this.fillColorArea.hostDialog=this;this.fillColorArea.onclick=function(){this.hostDialog.showFillColorDialog();};item.appendChild(this.fillColorArea);return item;};VectorPropertyWindow.prototype.onSelectionChanged=function(_40a){PropertyWindow.prototype.onSelectionChanged.call(this,_40a);if(_40a!=null&&(typeof _40a.getColor=="function")){if(_40a.getColor()!=null){this.lineColorArea.style.background=_40a.getColor().getHTMLStyle();}else{this.lineColorArea.style.background="transparent";}this.lineColorArea.style.cursor="pointer";this.lineColorArea.style.border="1px solid gray";this.lineColorLabel.style.color="black";}else{this.lineColorArea.style.background="transparent";this.lineColorArea.style.cursor=null;this.lineColorArea.style.border="1px solid #d0d0d0";this.lineColorLabel.style.color="#d0d0d0";}if(_40a!=null&&(typeof _40a.getBackgroundColor=="function")){if(_40a.getBackgroundColor()!=null){this.fillColorArea.style.background=_40a.getBackgroundColor().getHTMLStyle();}else{this.fillColorArea.style.background="transparent";}this.fillColorArea.style.cursor="pointer";this.fillColorArea.style.border="1px solid gray";this.fillColorLabel.style.color="black";}else{this.fillColorArea.style.background="transparent";this.fillColorArea.style.cursor=null;this.fillColorArea.style.border="1px solid #d0d0d0";this.fillColorLabel.style.color="#d0d0d0";}};VectorPropertyWindow.prototype.showLineColorDialog=function(){if((this.getCurrentSelection()==null)||(typeof this.getCurrentSelection().getColor!="function")){return;}var _40b=new LineColorDialog(this.getCurrentSelection());_40b.setColor(this.getCurrentSelection().getColor());this.workflow.showDialog(_40b);};VectorPropertyWindow.prototype.showFillColorDialog=function(){if(typeof this.getCurrentSelection().getBackgroundColor!="function"){return;}var _40c=new BackgroundColorDialog(this.getCurrentSelection());_40c.setColor(this.getCurrentSelection().getBackgroundColor());this.workflow.showDialog(_40c);};