/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

ArrayList=function(){this.increment=10;this.size=0;this.data=new Array(this.increment);};ArrayList.EMPTY_LIST=new ArrayList();ArrayList.prototype.reverse=function(){var _1131=new Array(this.size);for(var i=0;i<this.size;i++){_1131[i]=this.data[this.size-i-1];}this.data=_1131;};ArrayList.prototype.getCapacity=function(){return this.data.length;};ArrayList.prototype.getSize=function(){return this.size;};ArrayList.prototype.isEmpty=function(){return this.getSize()==0;};ArrayList.prototype.getLastElement=function(){if(this.data[this.getSize()-1]!=null){return this.data[this.getSize()-1];}};ArrayList.prototype.getFirstElement=function(){if(this.data[0]!=null){return this.data[0];}};ArrayList.prototype.get=function(i){return this.data[i];};ArrayList.prototype.add=function(obj){if(this.getSize()==this.data.length){this.resize();}this.data[this.size++]=obj;};ArrayList.prototype.addAll=function(obj){for(var i=0;i<obj.getSize();i++){this.add(obj.get(i));}};ArrayList.prototype.remove=function(obj){var index=this.indexOf(obj);if(index>=0){return this.removeElementAt(index);}return null;};ArrayList.prototype.insertElementAt=function(obj,index){if(this.size==this.capacity){this.resize();}for(var i=this.getSize();i>index;i--){this.data[i]=this.data[i-1];}this.data[index]=obj;this.size++;};ArrayList.prototype.removeElementAt=function(index){var _113d=this.data[index];for(var i=index;i<(this.getSize()-1);i++){this.data[i]=this.data[i+1];}this.data[this.getSize()-1]=null;this.size--;return _113d;};ArrayList.prototype.removeAllElements=function(){this.size=0;for(var i=0;i<this.data.length;i++){this.data[i]=null;}};ArrayList.prototype.indexOf=function(obj){for(var i=0;i<this.getSize();i++){if(this.data[i]==obj){return i;}}return -1;};ArrayList.prototype.contains=function(obj){for(var i=0;i<this.getSize();i++){if(this.data[i]==obj){return true;}}return false;};ArrayList.prototype.resize=function(){newData=new Array(this.data.length+this.increment);for(var i=0;i<this.data.length;i++){newData[i]=this.data[i];}this.data=newData;};ArrayList.prototype.trimToSize=function(){var temp=new Array(this.getSize());for(var i=0;i<this.getSize();i++){temp[i]=this.data[i];}this.size=temp.length-1;this.data=temp;};ArrayList.prototype.sort=function(f){var i,j;var _1149;var _114a;var _114b;var _114c;for(i=1;i<this.getSize();i++){_114a=this.data[i];_1149=_114a[f];j=i-1;_114b=this.data[j];_114c=_114b[f];while(j>=0&&_114c>_1149){this.data[j+1]=this.data[j];j--;if(j>=0){_114b=this.data[j];_114c=_114b[f];}}this.data[j+1]=_114a;}};ArrayList.prototype.clone=function(){var _114d=new ArrayList(this.size);for(var i=0;i<this.size;i++){_114d.add(this.data[i]);}return _114d;};ArrayList.prototype.overwriteElementAt=function(obj,index){this.data[index]=obj;};