/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

Canvas=function(_11c3){if(_11c3){this.construct(_11c3);}this.enableSmoothFigureHandling=false;this.canvasLines=new ArrayList();};Canvas.prototype.type="Canvas";Canvas.prototype.construct=function(_11c4){this.canvasId=_11c4;this.html=document.getElementById(this.canvasId);this.scrollArea=document.body.parentNode;};Canvas.prototype.setViewPort=function(divId){this.scrollArea=document.getElementById(divId);};Canvas.prototype.addFigure=function(_11c6,xPos,yPos,_11c9){if(this.enableSmoothFigureHandling==true){if(_11c6.timer<=0){_11c6.setAlpha(0.001);}var _11ca=_11c6;var _11cb=function(){if(_11ca.alpha<1){_11ca.setAlpha(Math.min(1,_11ca.alpha+0.05));}else{window.clearInterval(_11ca.timer);_11ca.timer=-1;}};if(_11ca.timer>0){window.clearInterval(_11ca.timer);}_11ca.timer=window.setInterval(_11cb,30);}_11c6.setCanvas(this);if(xPos&&yPos){_11c6.setPosition(xPos,yPos);}if(_11c6 instanceof Line){this.canvasLines.add(_11c6);this.html.appendChild(_11c6.getHTMLElement());}else{var obj=this.canvasLines.getFirstElement();if(obj==null){this.html.appendChild(_11c6.getHTMLElement());}else{this.html.insertBefore(_11c6.getHTMLElement(),obj.getHTMLElement());}}if(!_11c9){_11c6.paint();}};Canvas.prototype.removeFigure=function(_11cd){if(this.enableSmoothFigureHandling==true){var oThis=this;var _11cf=_11cd;var _11d0=function(){if(_11cf.alpha>0){_11cf.setAlpha(Math.max(0,_11cf.alpha-0.05));}else{window.clearInterval(_11cf.timer);_11cf.timer=-1;oThis.html.removeChild(_11cf.html);_11cf.setCanvas(null);}};if(_11cf.timer>0){window.clearInterval(_11cf.timer);}_11cf.timer=window.setInterval(_11d0,20);}else{this.html.removeChild(_11cd.html);_11cd.setCanvas(null);}if(_11cd instanceof Line){this.canvasLines.remove(_11cd);}};Canvas.prototype.getEnableSmoothFigureHandling=function(){return this.enableSmoothFigureHandling;};Canvas.prototype.setEnableSmoothFigureHandling=function(flag){this.enableSmoothFigureHandling=flag;};Canvas.prototype.getWidth=function(){return parseInt(this.html.style.width);};Canvas.prototype.getHeight=function(){return parseInt(this.html.style.height);};Canvas.prototype.setBackgroundImage=function(_11d2,_11d3){if(_11d2!=null){if(_11d3){this.html.style.background="transparent url("+_11d2+") ";}else{this.html.style.background="transparent url("+_11d2+") no-repeat";}}else{this.html.style.background="transparent";}};Canvas.prototype.getY=function(){return this.y;};Canvas.prototype.getX=function(){return this.x;};Canvas.prototype.getAbsoluteY=function(){var el=this.html;var ot=el.offsetTop;while((el=el.offsetParent)!=null){ot+=el.offsetTop;}return ot;};Canvas.prototype.getAbsoluteX=function(){var el=this.html;var ol=el.offsetLeft;while((el=el.offsetParent)!=null){ol+=el.offsetLeft;}return ol;};Canvas.prototype.getScrollLeft=function(){return this.scrollArea.scrollLeft;};Canvas.prototype.getScrollTop=function(){return this.scrollArea.scrollTop;};