/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

CommandStack=function(){this.undostack=new Array();this.redostack=new Array();this.maxundo=50;this.eventListeners=new ArrayList();};CommandStack.PRE_EXECUTE=1;CommandStack.PRE_REDO=2;CommandStack.PRE_UNDO=4;CommandStack.POST_EXECUTE=8;CommandStack.POST_REDO=16;CommandStack.POST_UNDO=32;CommandStack.POST_MASK=CommandStack.POST_EXECUTE|CommandStack.POST_UNDO|CommandStack.POST_REDO;CommandStack.PRE_MASK=CommandStack.PRE_EXECUTE|CommandStack.PRE_UNDO|CommandStack.PRE_REDO;CommandStack.prototype.type="CommandStack";CommandStack.prototype.setUndoLimit=function(count){this.maxundo=count;};CommandStack.prototype.markSaveLocation=function(){this.undostack=new Array();this.redostack=new Array();};CommandStack.prototype.execute=function(_12d6){if(_12d6.canExecute()==false){return;}this.notifyListeners(_12d6,CommandStack.PRE_EXECUTE);this.undostack.push(_12d6);_12d6.execute();this.redostack=new Array();if(this.undostack.length>this.maxundo){this.undostack=this.undostack.slice(this.undostack.length-this.maxundo);}this.notifyListeners(_12d6,CommandStack.POST_EXECUTE);};CommandStack.prototype.undo=function(){var _12d7=this.undostack.pop();if(_12d7){this.notifyListeners(_12d7,CommandStack.PRE_UNDO);this.redostack.push(_12d7);_12d7.undo();this.notifyListeners(_12d7,CommandStack.POST_UNDO);}};CommandStack.prototype.redo=function(){var _12d8=this.redostack.pop();if(_12d8){this.notifyListeners(_12d8,CommandStack.PRE_REDO);this.undostack.push(_12d8);_12d8.redo();this.notifyListeners(_12d8,CommandStack.POST_REDO);}};CommandStack.prototype.canRedo=function(){return this.redostack.length>0;};CommandStack.prototype.canUndo=function(){return this.undostack.length>0;};CommandStack.prototype.addCommandStackEventListener=function(_12d9){this.eventListeners.add(_12d9);};CommandStack.prototype.removeCommandStackEventListener=function(_12da){this.eventListeners.remove(_12da);};CommandStack.prototype.notifyListeners=function(_12db,state){var event=new CommandStackEvent(_12db,state);var size=this.eventListeners.getSize();for(var i=0;i<size;i++){this.eventListeners.get(i).stackChanged(event);}};