/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

Dialog=function(_526){this.buttonbar=null;if(_526){Window.call(this,_526);}else{Window.call(this,"Dialog");}this.setDimension(400,300);};Dialog.prototype=new Window;Dialog.prototype.type="Dialog";Dialog.prototype.createHTMLElement=function(){var item=Window.prototype.createHTMLElement.call(this);var _528=this;this.buttonbar=document.createElement("div");this.buttonbar.style.position="absolute";this.buttonbar.style.left="0px";this.buttonbar.style.bottom="0px";this.buttonbar.style.width=this.getWidth()+"px";this.buttonbar.style.height="30px";this.buttonbar.style.margin="0px";this.buttonbar.style.padding="0px";this.buttonbar.style.font="normal 10px verdana";this.buttonbar.style.backgroundColor="#c0c0c0";this.buttonbar.style.borderBottom="2px solid gray";this.buttonbar.style.whiteSpace="nowrap";this.buttonbar.style.textAlign="center";this.okbutton=document.createElement("button");this.okbutton.style.border="1px solid gray";this.okbutton.style.font="normal 10px verdana";this.okbutton.style.width="80px";this.okbutton.style.margin="5px";this.okbutton.innerHTML="Ok";this.okbutton.onclick=function(){_528.onOk();};this.buttonbar.appendChild(this.okbutton);this.cancelbutton=document.createElement("button");this.cancelbutton.innerHTML="Cancel";this.cancelbutton.style.font="normal 10px verdana";this.cancelbutton.style.border="1px solid gray";this.cancelbutton.style.width="80px";this.cancelbutton.style.margin="5px";this.cancelbutton.onclick=function(){_528.onCancel();};this.buttonbar.appendChild(this.cancelbutton);item.appendChild(this.buttonbar);return item;};Dialog.prototype.onOk=function(){this.workflow.removeFigure(this);};Dialog.prototype.onCancel=function(){this.workflow.removeFigure(this);};Dialog.prototype.setDimension=function(w,h){Window.prototype.setDimension.call(this,w,h);if(this.buttonbar!=null){this.buttonbar.style.width=this.getWidth()+"px";}};Dialog.prototype.setWorkflow=function(_52b){Window.prototype.setWorkflow.call(this,_52b);this.setFocus();};Dialog.prototype.setFocus=function(){};Dialog.prototype.onSetDocumentDirty=function(){};