/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

Graphics=function(_dcb,_dcc,_dcd){this.jsGraphics=_dcb;this.xt=_dcd.x;this.yt=_dcd.y;this.radian=_dcc*Math.PI/180;this.sinRadian=Math.sin(this.radian);this.cosRadian=Math.cos(this.radian);};Graphics.prototype.setStroke=function(x){this.jsGraphics.setStroke(x);};Graphics.prototype.drawLine=function(x1,y1,x2,y2){var _x1=this.xt+x1*this.cosRadian-y1*this.sinRadian;var _y1=this.yt+x1*this.sinRadian+y1*this.cosRadian;var _x2=this.xt+x2*this.cosRadian-y2*this.sinRadian;var _y2=this.yt+x2*this.sinRadian+y2*this.cosRadian;this.jsGraphics.drawLine(_x1,_y1,_x2,_y2);};Graphics.prototype.fillRect=function(x,y,w,h){var x1=this.xt+x*this.cosRadian-y*this.sinRadian;var y1=this.yt+x*this.sinRadian+y*this.cosRadian;var x2=this.xt+(x+w)*this.cosRadian-y*this.sinRadian;var y2=this.yt+(x+w)*this.sinRadian+y*this.cosRadian;var x3=this.xt+(x+w)*this.cosRadian-(y+h)*this.sinRadian;var y3=this.yt+(x+w)*this.sinRadian+(y+h)*this.cosRadian;var x4=this.xt+x*this.cosRadian-(y+h)*this.sinRadian;var y4=this.yt+x*this.sinRadian+(y+h)*this.cosRadian;this.jsGraphics.fillPolygon([x1,x2,x3,x4],[y1,y2,y3,y4]);};Graphics.prototype.fillPolygon=function(_de3,_de4){var rotX=new Array();var rotY=new Array();for(var i=0;i<_de3.length;i++){rotX[i]=this.xt+_de3[i]*this.cosRadian-_de4[i]*this.sinRadian;rotY[i]=this.yt+_de3[i]*this.sinRadian+_de4[i]*this.cosRadian;}this.jsGraphics.fillPolygon(rotX,rotY);};Graphics.prototype.setColor=function(_de8){this.jsGraphics.setColor(_de8.getHTMLStyle());};Graphics.prototype.drawPolygon=function(_de9,_dea){var rotX=new Array();var rotY=new Array();for(var i=0;i<_de9.length;i++){rotX[i]=this.xt+_de9[i]*this.cosRadian-_dea[i]*this.sinRadian;rotY[i]=this.yt+_de9[i]*this.sinRadian+_dea[i]*this.cosRadian;}this.jsGraphics.drawPolygon(rotX,rotY);};