/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

LineEndResizeHandle=function(_1294){Rectangle.call(this);this.setDimension(10,10);this.setBackgroundColor(new Color(0,255,0));this.setWorkflow(_1294);this.setZOrder(10000);};LineEndResizeHandle.prototype=new Rectangle;LineEndResizeHandle.prototype.type="LineEndResizeHandle";LineEndResizeHandle.prototype.onDragend=function(){var line=this.workflow.currentSelection;if(line instanceof Connection){var end=line.targetAnchor.getLocation(line.sourceAnchor.getReferencePoint());line.setEndPoint(end.x,end.y);this.getWorkflow().showLineResizeHandles(line);line.setRouter(line.oldRouter);}else{if(this.command==null){return;}var x1=line.getStartX();var y1=line.getStartY();var x2=line.getEndX();var y2=line.getEndY();this.command.setEndPoints(x1,y1,x2,y2);this.workflow.getCommandStack().execute(this.command);this.command=null;}};LineEndResizeHandle.prototype.onDragstart=function(x,y){if(!this.canDrag){return false;}var line=this.workflow.currentSelection;if(line instanceof Connection){this.command=new CommandReconnect(line);line.oldRouter=line.getRouter();line.setRouter(new NullConnectionRouter());}else{var x1=line.getStartX();var y1=line.getStartY();var x2=line.getEndX();var y2=line.getEndY();this.command=new CommandMoveLine(line,x1,y1,x2,y2);}return true;};LineEndResizeHandle.prototype.onDrag=function(){var oldX=this.getX();var oldY=this.getY();Rectangle.prototype.onDrag.call(this);var diffX=oldX-this.getX();var diffY=oldY-this.getY();var _12a6=this.workflow.currentSelection.getEndPoint();var line=this.workflow.currentSelection;line.setEndPoint(_12a6.x-diffX,_12a6.y-diffY);line.isMoving=true;};LineEndResizeHandle.prototype.onDrop=function(_12a8){var line=this.workflow.currentSelection;line.isMoving=false;if(line instanceof Connection){this.command.setNewPorts(line.getSource(),_12a8);this.getWorkflow().getCommandStack().execute(this.command);}this.command=null;};LineEndResizeHandle.prototype.onKeyDown=function(_12aa){if(this.workflow!=null){this.workflow.onKeyDown(_12aa);}};LineEndResizeHandle.prototype.fireMoveEvent=function(){};