/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

LineStartResizeHandle=function(_1463){Rectangle.call(this);this.setDimension(10,10);this.setBackgroundColor(new Color(0,255,0));this.setWorkflow(_1463);this.setZOrder(10000);};LineStartResizeHandle.prototype=new Rectangle;LineStartResizeHandle.prototype.type="LineStartResizeHandle";LineStartResizeHandle.prototype.onDragend=function(){var line=this.workflow.currentSelection;if(line instanceof Connection){var start=line.sourceAnchor.getLocation(line.targetAnchor.getReferencePoint());line.setStartPoint(start.x,start.y);this.getWorkflow().showLineResizeHandles(line);line.setRouter(line.oldRouter);}else{if(this.command==null){return;}var x1=line.getStartX();var y1=line.getStartY();var x2=line.getEndX();var y2=line.getEndY();this.command.setEndPoints(x1,y1,x2,y2);this.getWorkflow().getCommandStack().execute(this.command);this.command=null;}};LineStartResizeHandle.prototype.onDragstart=function(x,y){if(!this.canDrag){return false;}var line=this.workflow.currentSelection;if(line instanceof Connection){this.command=new CommandReconnect(line);line.oldRouter=line.getRouter();line.setRouter(new NullConnectionRouter());}else{var x1=line.getStartX();var y1=line.getStartY();var x2=line.getEndX();var y2=line.getEndY();this.command=new CommandMoveLine(line,x1,y1,x2,y2);}return true;};LineStartResizeHandle.prototype.onDrag=function(){var oldX=this.getX();var oldY=this.getY();Rectangle.prototype.onDrag.call(this);var diffX=oldX-this.getX();var diffY=oldY-this.getY();var _1475=this.workflow.currentSelection.getStartPoint();var line=this.workflow.currentSelection;line.setStartPoint(_1475.x-diffX,_1475.y-diffY);line.isMoving=true;};LineStartResizeHandle.prototype.onDrop=function(_1477){var line=this.workflow.currentSelection;line.isMoving=false;if(line instanceof Connection){this.command.setNewPorts(_1477,line.getTarget());this.getWorkflow().getCommandStack().execute(this.command);}this.command=null;};LineStartResizeHandle.prototype.onKeyDown=function(_1479,ctrl){if(this.workflow!=null){this.workflow.onKeyDown(_1479,ctrl);}};LineStartResizeHandle.prototype.fireMoveEvent=function(){};