/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

Menu=function(){this.menuItems=new ArrayList();Figure.call(this);this.setSelectable(false);this.setDeleteable(false);this.setCanDrag(false);this.setResizeable(false);this.setSelectable(false);this.setZOrder(10000);this.dirty=false;};Menu.prototype=new Figure;Menu.prototype.type="Menu";Menu.prototype.createHTMLElement=function(){var item=document.createElement("div");item.style.position="absolute";item.style.left=this.x+"px";item.style.top=this.y+"px";item.style.margin="0px";item.style.padding="0px";item.style.zIndex=""+Figure.ZOrderBaseIndex;item.style.border="1px solid gray";item.style.background="lavender";item.style.cursor="pointer";return item;};Menu.prototype.setWorkflow=function(_155e){this.workflow=_155e;};Menu.prototype.appendMenuItem=function(item){this.menuItems.add(item);item.parentMenu=this;this.dirty=true;};Menu.prototype.getHTMLElement=function(){var html=Figure.prototype.getHTMLElement.call(this);if(this.dirty){this.createList();}return html;};Menu.prototype.createList=function(){this.dirty=false;this.html.innerHTML="";var oThis=this;for(var i=0;i<this.menuItems.getSize();i++){var item=this.menuItems.get(i);var li=document.createElement("a");li.innerHTML=item.getLabel();li.style.display="block";li.style.fontFamily="Verdana, Arial, Helvetica, sans-serif";li.style.fontSize="9pt";li.style.color="dimgray";li.style.borderBottom="1px solid silver";li.style.paddingLeft="5px";li.style.paddingRight="5px";li.style.cursor="pointer";this.html.appendChild(li);li.menuItem=item;if(li.addEventListener){li.addEventListener("click",function(event){var _1566=arguments[0]||window.event;_1566.cancelBubble=true;_1566.returnValue=false;var diffX=_1566.clientX;var diffY=_1566.clientY;var _1569=document.body.parentNode.scrollLeft;var _156a=document.body.parentNode.scrollTop;this.menuItem.execute(diffX+_1569,diffY+_156a);},false);li.addEventListener("mouseup",function(event){event.cancelBubble=true;event.returnValue=false;},false);li.addEventListener("mousedown",function(event){event.cancelBubble=true;event.returnValue=false;},false);li.addEventListener("mouseover",function(event){this.style.backgroundColor="silver";},false);li.addEventListener("mouseout",function(event){this.style.backgroundColor="transparent";},false);}else{if(li.attachEvent){li.attachEvent("onclick",function(event){var _1570=arguments[0]||window.event;_1570.cancelBubble=true;_1570.returnValue=false;var diffX=_1570.clientX;var diffY=_1570.clientY;var _1573=document.body.parentNode.scrollLeft;var _1574=document.body.parentNode.scrollTop;event.srcElement.menuItem.execute(diffX+_1573,diffY+_1574);});li.attachEvent("onmousedown",function(event){event.cancelBubble=true;event.returnValue=false;});li.attachEvent("onmouseup",function(event){event.cancelBubble=true;event.returnValue=false;});li.attachEvent("onmouseover",function(event){event.srcElement.style.backgroundColor="silver";});li.attachEvent("onmouseout",function(event){event.srcElement.style.backgroundColor="transparent";});}}}};