/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

Node=function(){this.bgColor=null;this.lineColor=new Color(128,128,255);this.lineStroke=1;this.ports=new ArrayList();Figure.call(this);};Node.prototype=new Figure;Node.prototype.type="Node";Node.prototype.dispose=function(){for(var i=0;i<this.ports.getSize();i++){this.ports.get(i).dispose();}this.ports=null;Figure.prototype.dispose.call(this);};Node.prototype.createHTMLElement=function(){var item=Figure.prototype.createHTMLElement.call(this);item.style.width="auto";item.style.height="auto";item.style.margin="0px";item.style.padding="0px";if(this.lineColor!=null){item.style.border=this.lineStroke+"px solid "+this.lineColor.getHTMLStyle();}item.style.fontSize="1px";if(this.bgColor!=null){item.style.backgroundColor=this.bgColor.getHTMLStyle();}return item;};Node.prototype.paint=function(){Figure.prototype.paint.call(this);for(var i=0;i<this.ports.getSize();i++){this.ports.get(i).paint();}};Node.prototype.getPorts=function(){return this.ports;};Node.prototype.getPort=function(_611){if(this.ports==null){return null;}for(var i=0;i<this.ports.getSize();i++){var port=this.ports.get(i);if(port.getName()==_611){return port;}}};Node.prototype.addPort=function(port,x,y){this.ports.add(port);port.setOrigin(x,y);port.setPosition(x,y);port.setParent(this);port.setDeleteable(false);this.html.appendChild(port.getHTMLElement());if(this.workflow!=null){this.workflow.registerPort(port);}};Node.prototype.removePort=function(port){if(this.ports!=null){this.ports.removeElementAt(this.ports.indexOf(port));}try{this.html.removeChild(port.getHTMLElement());}catch(exc){}if(this.workflow!=null){this.workflow.unregisterPort(port);}};Node.prototype.setWorkflow=function(_618){var _619=this.workflow;Figure.prototype.setWorkflow.call(this,_618);if(_619!=null){for(var i=0;i<this.ports.getSize();i++){_619.unregisterPort(this.ports.get(i));}}if(this.workflow!=null){for(var i=0;i<this.ports.getSize();i++){this.workflow.registerPort(this.ports.get(i));}}};Node.prototype.setBackgroundColor=function(_61b){this.bgColor=_61b;if(this.bgColor!=null){this.html.style.backgroundColor=this.bgColor.getHTMLStyle();}else{this.html.style.backgroundColor="transparent";}};Node.prototype.getBackgroundColor=function(){return this.bgColor;};Node.prototype.setColor=function(_61c){this.lineColor=_61c;if(this.lineColor!=null){this.html.style.border=this.lineStroke+"px solid "+this.lineColor.getHTMLStyle();}else{this.html.style.border="0px";}};Node.prototype.setLineWidth=function(w){this.lineStroke=w;if(this.lineColor!=null){this.html.style.border=this.lineStroke+"px solid "+this.lineColor.getHTMLStyle();}else{this.html.style.border="0px";}};