/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

OutputPort=function(_8e9){Port.call(this,_8e9);this.maxFanOut=100;};OutputPort.prototype=new Port;OutputPort.prototype.type="OutputPort";OutputPort.prototype.onDrop=function(port){if(this.getMaxFanOut()<=this.getFanOut()){return;}if(this.parentNode.id==port.parentNode.id){}else{if(port instanceof InputPort){var _8eb=new CommandConnect(this.parentNode.workflow,this,port);this.parentNode.workflow.getCommandStack().execute(_8eb);}}};OutputPort.prototype.onDragEnter=function(port){if(this.getMaxFanOut()<=this.getFanOut()){return;}if(port instanceof InputPort){Port.prototype.onDragEnter.call(this,port);}else{if(port instanceof LineStartResizeHandle){var line=this.workflow.currentSelection;if(line instanceof Connection&&line.getSource() instanceof OutputPort){Port.prototype.onDragEnter.call(this,line.getSource());}}else{if(port instanceof LineEndResizeHandle){var line=this.workflow.currentSelection;if(line instanceof Connection&&line.getTarget() instanceof OutputPort){Port.prototype.onDragEnter.call(this,line.getTarget());}}}}};OutputPort.prototype.onDragLeave=function(port){if(port instanceof InputPort){Port.prototype.onDragLeave.call(this,port);}else{if(port instanceof LineStartResizeHandle){var line=this.workflow.currentSelection;if(line instanceof Connection&&line.getSource() instanceof OutputPort){Port.prototype.onDragLeave.call(this,line.getSource());}}else{if(port instanceof LineEndResizeHandle){var line=this.workflow.currentSelection;if(line instanceof Connection&&line.getTarget() instanceof OutputPort){Port.prototype.onDragLeave.call(this,line.getTarget());}}}}};OutputPort.prototype.onDragstart=function(x,y){if(this.maxFanOut==-1){return true;}if(this.getMaxFanOut()<=this.getFanOut()){return false;}return true;};OutputPort.prototype.setMaxFanOut=function(_8f2){this.maxFanOut=_8f2;};OutputPort.prototype.getMaxFanOut=function(){return this.maxFanOut;};OutputPort.prototype.getFanOut=function(){if(this.getParent().workflow==null){return 0;}var _8f3=0;var _8f4=this.getParent().workflow.getLines();var size=_8f4.getSize();for(var i=0;i<size;i++){var line=_8f4.get(i);if(line instanceof Connection){if(line.getSource()==this){_8f3++;}else{if(line.getTarget()==this){_8f3++;}}}}return _8f3;};