/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

PropertyWindow=function(){this.currentSelection=null;Window.call(this,"Property Window");this.setDimension(200,100);};PropertyWindow.prototype=new Window;PropertyWindow.prototype.type="PropertyWindow";PropertyWindow.prototype.dispose=function(){Window.prototype.dispose.call(this);};PropertyWindow.prototype.createHTMLElement=function(){var item=Window.prototype.createHTMLElement.call(this);item.appendChild(this.createLabel("Type:",15,25));item.appendChild(this.createLabel("X :",15,50));item.appendChild(this.createLabel("Y :",15,70));item.appendChild(this.createLabel("Width :",85,50));item.appendChild(this.createLabel("Height :",85,70));this.labelType=this.createLabel("",50,25);this.labelX=this.createLabel("",40,50);this.labelY=this.createLabel("",40,70);this.labelWidth=this.createLabel("",135,50);this.labelHeight=this.createLabel("",135,70);this.labelType.style.fontWeight="normal";this.labelX.style.fontWeight="normal";this.labelY.style.fontWeight="normal";this.labelWidth.style.fontWeight="normal";this.labelHeight.style.fontWeight="normal";item.appendChild(this.labelType);item.appendChild(this.labelX);item.appendChild(this.labelY);item.appendChild(this.labelWidth);item.appendChild(this.labelHeight);return item;};PropertyWindow.prototype.onSelectionChanged=function(_539){Window.prototype.onSelectionChanged.call(this,_539);if(this.currentSelection!=null){this.currentSelection.detachMoveListener(this);}this.currentSelection=_539;if(_539!=null&&_539!=this){this.labelType.innerHTML=_539.type;if(_539.getX){this.labelX.innerHTML=_539.getX();this.labelY.innerHTML=_539.getY();this.labelWidth.innerHTML=_539.getWidth();this.labelHeight.innerHTML=_539.getHeight();this.currentSelection=_539;this.currentSelection.attachMoveListener(this);}else{this.labelX.innerHTML="";this.labelY.innerHTML="";this.labelWidth.innerHTML="";this.labelHeight.innerHTML="";}}else{this.labelType.innerHTML="&lt;none&gt;";this.labelX.innerHTML="";this.labelY.innerHTML="";this.labelWidth.innerHTML="";this.labelHeight.innerHTML="";}};PropertyWindow.prototype.getCurrentSelection=function(){return this.currentSelection;};PropertyWindow.prototype.onOtherFigureMoved=function(_53a){if(_53a==this.currentSelection){this.onSelectionChanged(_53a);}};PropertyWindow.prototype.createLabel=function(text,x,y){var l=document.createElement("div");l.style.position="absolute";l.style.left=x+"px";l.style.top=y+"px";l.style.font="normal 10px verdana";l.style.whiteSpace="nowrap";l.style.fontWeight="bold";l.innerHTML=text;return l;};