/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

Rectangle=function(width,_119f){this.bgColor=null;this.lineColor=new Color(0,0,0);this.lineStroke=1;Figure.call(this);if(width&&_119f){this.setDimension(width,_119f);}};Rectangle.prototype=new Figure;Rectangle.prototype.type="Rectangle";Rectangle.prototype.dispose=function(){Figure.prototype.dispose.call(this);this.bgColor=null;this.lineColor=null;};Rectangle.prototype.createHTMLElement=function(){var item=Figure.prototype.createHTMLElement.call(this);item.style.width="auto";item.style.height="auto";item.style.margin="0px";item.style.padding="0px";item.style.border=this.lineStroke+"px solid "+this.lineColor.getHTMLStyle();item.style.fontSize="1px";item.style.lineHeight="1px";item.innerHTML="&nbsp";if(this.bgColor!=null){item.style.backgroundColor=this.bgColor.getHTMLStyle();}return item;};Rectangle.prototype.setBackgroundColor=function(color){this.bgColor=color;if(this.bgColor!=null){this.html.style.backgroundColor=this.bgColor.getHTMLStyle();}else{this.html.style.backgroundColor="transparent";}};Rectangle.prototype.getBackgroundColor=function(){return this.bgColor;};Rectangle.prototype.setColor=function(color){this.lineColor=color;if(this.lineColor!=null){this.html.style.border=this.lineStroke+"px solid "+this.lineColor.getHTMLStyle();}else{this.html.style.border=this.lineStroke+"0px";}};Rectangle.prototype.getColor=function(){return this.lineColor;};Rectangle.prototype.getWidth=function(){return Figure.prototype.getWidth.call(this)+2*this.lineStroke;};Rectangle.prototype.getHeight=function(){return Figure.prototype.getHeight.call(this)+2*this.lineStroke;};Rectangle.prototype.setDimension=function(w,h){return Figure.prototype.setDimension.call(this,w-2*this.lineStroke,h-2*this.lineStroke);};Rectangle.prototype.setLineWidth=function(w){var diff=w-this.lineStroke;this.setDimension(this.getWidth()-2*diff,this.getHeight()-2*diff);this.lineStroke=w;var c="transparent";if(this.lineColor!=null){c=this.lineColor.getHTMLStyle();}this.html.style.border=this.lineStroke+"px solid "+c;};Rectangle.prototype.getLineWidth=function(){return this.lineStroke;};