/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

OverviewWindow=function(name){Window.call(this,"Overview Window");this.setDimension(180,150);this.servers=new Object();this.name=name;};OverviewWindow.prototype=new Window;OverviewWindow.prototype.type="OverviewWindow";OverviewWindow.prototype.createHTMLElement=function(){var item=Window.prototype.createHTMLElement.call(this);this.inputDiv=document.createElement("div");this.inputDiv.style.position="absolute";this.inputDiv.style.left="10px";this.inputDiv.style.top="20px";this.inputDiv.style.overflow="auto";this.inputDiv.style.border="1px solid black";this.inputDiv.style.font="normal 10px verdana";item.appendChild(this.inputDiv);return item;};OverviewWindow.prototype.setDimension=function(w,h){Window.prototype.setDimension.call(this,w,h);if(this.inputDiv!=null){this.inputDiv.style.height=(h-30)+"px";this.inputDiv.style.width=(w-20)+"px";}};OverviewWindow.prototype.addServer=function(_dc1){this.servers[_dc1.id]=_dc1;this.createList();};OverviewWindow.prototype.removeServer=function(_dc2){this.servers[_dc2.id]=null;this.createList();};OverviewWindow.prototype.createList=function(){this.inputDiv.innerHTML="";var list=document.createElement("ul");for(key in this.servers){var _dc4=this.servers[key];if(_dc4!=null){var li=document.createElement("li");var a=document.createElement("a");a.href="javascript:OverviewWindow.scrollTo('"+_dc4.id+"')";a.innerHTML=_dc4.ip;li.appendChild(a);if(_dc4.isReachable()){a.style.color="green";}else{a.style.color="red";a.style.fontWeight="bold";}list.appendChild(li);}}this.inputDiv.appendChild(list);};OverviewWindow.scrollTo=function(id){var _dc8=workflow.getFigure(id);workflow.scrollTo(_dc8.getX()-OverviewWindow.screenWidth()/2,_dc8.getY()-OverviewWindow.screenHeight()/2);};OverviewWindow.prototype.onDragend=function(){Window.prototype.onDragend.call(this);};OverviewWindow.screenWidth=function(){var _dc9=0;if(typeof (window.innerWidth)=="number"){_dc9=window.innerWidth;}else{if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){_dc9=document.documentElement.clientWidth;}else{if(document.body&&(document.body.clientWidth||document.body.clientHeight)){_dc9=document.body.clientWidth;}}}return _dc9;};OverviewWindow.screenHeight=function(){var _dca=0;if(typeof (window.innerWidth)=="number"){_dca=window.innerHeight;}else{if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){_dca=document.documentElement.clientHeight;}else{if(document.body&&(document.body.clientWidth||document.body.clientHeight)){_dca=document.body.clientHeight;}}}return _dca;};