tinyMCE.addI18n('sv.advanced',{
style_select:"Stilar",
font_size:"Teckenstorlek",
fontdefault:"Typsnittsfamilj",
block:"Format",
paragraph:"Punkt",
div:"Div",
address:"Address",
pre:"Förformaterad",
h1:"Rubrik 1",
h2:"Rubrik 2",
h3:"Rubrik 3",
h4:"Rubrik 4",
h5:"Rubrik 5",
h6:"Rubrik 6",
blockquote:"Blockquote",
code:"Kod",
samp:"Kod prov",
dt:"Definition uttrycket ",
dd:"Definition beskrivning",
bold_desc:"Fet (Ctrl+B)",
italic_desc:"Kursiv (Ctrl+I)",
underline_desc:"Understrykning (Ctrl+U)",
striketrough_desc:"Strykning",
justifyleft_desc:"Justera vänster",
justifycenter_desc:"Centrerad",
justifyright_desc:"Justera höger",
justifyfull_desc:"Rikta fullständig",
bullist_desc:"Onumrerad lista",
numlist_desc:"Ordnad lista",
outdent_desc:"Minska indrag",
indent_desc:"Indrag",
undo_desc:"Ångra (Ctrl+Z)",
redo_desc:"Gör (Ctrl+Y)",
link_desc:"Infoga/redigera länk",
unlink_desc:"Ta bort länken",
image_desc:"Infoga/redigera bild",
cleanup_desc:"Cleanup rörig kod",
code_desc:"Redigera HTML-källa",
sub_desc:"Nedsänkt",
sup_desc:"Upphöjd",
hr_desc:"Infoga horisontella linjalen",
removeformat_desc:"Ta bort formatering",
custom1_desc:"Din anpassade beskrivning här",
forecolor_desc:"Välj textfärg",
backcolor_desc:"Välj bakgrundsfärg",
charmap_desc:"Infoga specialtecken",
visualaid_desc:"Växla riktlinjer / osynliga element",
anchor_desc:"Infoga / redigera ankare",
cut_desc:"Klippa",
copy_desc:"Kopia",
paste_desc:"Klistra",
image_props_desc:"Bildegenskaper",
newdocument_desc:"Nytt dokument",
help_desc:"Hjälp",
blockquote_desc:"Blockquote",
clipboard_msg:"Kopiera/Klipp ut/Klistra är inte tillgänglig i Mozilla och Firefox.\r\nVill du veta mer om det här problemet?",
path:"Stig",
newdocument:"Är du säker på att du vill radera allt innehåll?",
toolbar_focus:"Hoppa till verktygsknappar - Alt+Q, Hoppa till redigeraren - Alt+Z, Hoppa till elementet väg - Alt+X",
more_colors:"Fler färger"
});