tinyMCE.addI18n('sv.advanced_dlg',{
about_title:"Om TinyMCE",
about_general:"Om",
about_help:"Hjälp",
about_license:"Licens",
about_plugins:"Insticks",
about_plugin:"Insticks",
about_author:"Författare",
about_version:"Version",
about_loaded:"Laddade insticks",
anchor_title:"Infoga/redigera ankare",
anchor_name:"Ankarnamn",
code_title:"HTML Källa Redaktör",
code_wordwrap:"Ord sjal",
colorpicker_title:"Välj en färg",
colorpicker_picker_tab:"Väljare",
colorpicker_picker_title:"Färgväljare",
colorpicker_palette_tab:"Paletten",
colorpicker_palette_title:"Paletten färger",
colorpicker_named_tab:"Uppkallad",
colorpicker_named_title:"Namngivna färger",
colorpicker_color:"Färg:",
colorpicker_name:"Namn:",
charmap_title:"Välj anpassade tecken",
image_title:"Infoga/redigera bild",
image_src:"Bild URL",
image_alt:"Bildbeskrivning",
image_list:"Bild listan",
image_border:"Gräns",
image_dimensions:"Dimensioner",
image_vspace:"Vertikalt utrymme",
image_hspace:"Horisontell utrymme",
image_align:"Anpassning",
image_align_baseline:"Baslinje",
image_align_top:"Topp",
image_align_middle:"Mitten",
image_align_bottom:"Botten",
image_align_texttop:"Text toppen",
image_align_textbottom:"Text botten",
image_align_left:"Vänster",
image_align_right:"Höger",
link_title:"Infoga/redigera länk",
link_url:"Länk URL",
link_target:"Mål",
link_target_same:"Öppna länk i samma fönster",
link_target_blank:"Öppna länken i ett nytt fönster",
link_titlefield:"Titel",
link_is_email:"Webbadressen som du angav verkar vara en e-postadress, vill du lägga önskad mailto: prefixet?",
link_is_external:"Webbadressen som du angav verkar extern länk, vill du lägga önskad http:// prefixet?",
link_list:"Länklista"
});