/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

FieldModel=function(name,label){this.name=name;this.label=label;};FieldModel.prototype.type="FieldModel";FieldModel.DBTYPE_TEXT="TEXT";FieldModel.DBTYPE_DOCUMENT="DOCUMENT";FieldModel.DBTYPE_INTEGER="INTEGER";FieldModel.DBTYPE_LONG="LONG";FieldModel.DBTYPE_FLOAT="FLOAT";FieldModel.DBTYPE_DOUBLE="DOUBLE";FieldModel.DBTYPE_DECIMAL="DECIMAL";FieldModel.DBTYPE_DATE="DATE";FieldModel.DBTYPE_TIME="TIME";FieldModel.DBTYPE_TIMESTAMP="TIMESTAMP";FieldModel.DBTYPE_LONGTEXT="LONGTEXT";FieldModel.DBTYPE_BINARY="BINARY";FieldModel.DBTYPE_ENUM="ENUM";FieldModel.DBTYPE_BOOLEAN="BOOLEAN";FieldModel.prototype.getLabel=function(){return this.label;};FieldModel.prototype.getName=function(){return this.name;};FieldModel.prototype.getExtendedDescriptionLabel=function(){if(this.getTypeName()==FieldModel.DBTYPE_TEXT){return this.getName()+" "+this.getTypeName()+"<"+this.getLengthAsString()+">";}return this.getName()+" "+this.getTypeName();};FieldModel.prototype.getTableModel=function(){return this.table;};FieldModel.prototype.getTypeName=function(){return this.typeModel.getName();};FieldModel.prototype.setTableModel=function(_2258){if(!(_2258 instanceof TableModel)){throw "Invalid parameter type in [FieldModel.prototype.setTableModel]";}this.table=_2258;};FieldModel.prototype.setTypeModel=function(_2259){if(!(_2259 instanceof FieldTypeModel)){throw "Invalid parameter type in [FieldModel.prototype.setTypeModel]";}this.typeModel=_2259;this.typeModel.setParent(this);};FieldModel.prototype.getTypeModel=function(){return this.typeModel;};FieldModel.prototype.getLengthAsString=function(){var _225a="";if(FieldModel.DBTYPE_TEXT==this.getTypeName()){_225a=Integer.toString(this.getTypeModel().getMaxLength());if(this.getTypeModel().getFixeLength()){_225a="["+_225a+"]";}}return _225a;};