/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.OverviewWindow=function(name){draw2d.Window.call(this,"Overview Window");this.setDimension(180,150);this.servers=new Object();this.name=name;};draw2d.OverviewWindow.prototype=new draw2d.Window;draw2d.OverviewWindow.prototype.type="OverviewWindow";draw2d.OverviewWindow.prototype.createHTMLElement=function(){var item=draw2d.Window.prototype.createHTMLElement.call(this);this.inputDiv=document.createElement("div");this.inputDiv.style.position="absolute";this.inputDiv.style.left="10px";this.inputDiv.style.top="20px";this.inputDiv.style.overflow="auto";this.inputDiv.style.border="1px solid black";this.inputDiv.style.font="normal 10px verdana";item.appendChild(this.inputDiv);return item;};draw2d.OverviewWindow.prototype.setDimension=function(w,h){draw2d.Window.prototype.setDimension.call(this,w,h);if(this.inputDiv!=null){this.inputDiv.style.height=(h-30)+"px";this.inputDiv.style.width=(w-20)+"px";}};draw2d.OverviewWindow.prototype.addServer=function(_272b){this.servers[_272b.id]=_272b;this.createList();};draw2d.OverviewWindow.prototype.removeServer=function(_272c){this.servers[_272c.id]=null;this.createList();};draw2d.OverviewWindow.prototype.createList=function(){this.inputDiv.innerHTML="";var list=document.createElement("ul");for(key in this.servers){var _272e=this.servers[key];if(_272e!=null){var li=document.createElement("li");var a=document.createElement("a");a.href="javascript:draw2d.OverviewWindow.scrollTo('"+_272e.id+"')";a.innerHTML=_272e.ip;li.appendChild(a);if(_272e.isReachable()){a.style.color="green";}else{a.style.color="red";a.style.fontWeight="bold";}list.appendChild(li);}}this.inputDiv.appendChild(list);};draw2d.OverviewWindow.scrollTo=function(id){var _2732=workflow.getFigure(id);workflow.scrollTo(_2732.getX()-draw2d.OverviewWindow.screenWidth()/2,_2732.getY()-draw2d.OverviewWindow.screenHeight()/2);};draw2d.OverviewWindow.prototype.onDragend=function(){draw2d.Window.prototype.onDragend.call(this);};draw2d.OverviewWindow.screenWidth=function(){var _2733=0;if(typeof (window.innerWidth)=="number"){_2733=window.innerWidth;}else{if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){_2733=document.documentElement.clientWidth;}else{if(document.body&&(document.body.clientWidth||document.body.clientHeight)){_2733=document.body.clientWidth;}}}return _2733;};draw2d.OverviewWindow.screenHeight=function(){var _2734=0;if(typeof (window.innerWidth)=="number"){_2734=window.innerHeight;}else{if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){_2734=document.documentElement.clientHeight;}else{if(document.body&&(document.body.clientWidth||document.body.clientHeight)){_2734=document.body.clientHeight;}}}return _2734;};