/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.CompartmentFigure=function(){draw2d.Node.call(this);this.children=new draw2d.ArrayList();this.setBorder(new draw2d.LineBorder(1));this.dropable=new draw2d.DropTarget(this.html);this.dropable.node=this;this.dropable.addEventListener("figureenter",function(_1689){_1689.target.node.onFigureEnter(_1689.relatedTarget.node);});this.dropable.addEventListener("figureleave",function(_168a){_168a.target.node.onFigureLeave(_168a.relatedTarget.node);});this.dropable.addEventListener("figuredrop",function(_168b){_168b.target.node.onFigureDrop(_168b.relatedTarget.node);});};draw2d.CompartmentFigure.prototype=new draw2d.Node;draw2d.CompartmentFigure.prototype.type="CompartmentFigure";draw2d.CompartmentFigure.prototype.onFigureEnter=function(_168c){};draw2d.CompartmentFigure.prototype.onFigureLeave=function(_168d){};draw2d.CompartmentFigure.prototype.onFigureDrop=function(_168e){};draw2d.CompartmentFigure.prototype.getChildren=function(){return this.children;};draw2d.CompartmentFigure.prototype.addChild=function(_168f){_168f.setZOrder(this.getZOrder()+1);_168f.setParent(this);this.children.add(_168f);};draw2d.CompartmentFigure.prototype.removeChild=function(_1690){_1690.setParent(null);this.children.remove(_1690);};draw2d.CompartmentFigure.prototype.setZOrder=function(index){draw2d.Node.prototype.setZOrder.call(this,index);for(var i=0;i<this.children.getSize();i++){this.children.get(i).setZOrder(index+1);}};draw2d.CompartmentFigure.prototype.setPosition=function(xPos,yPos){var oldX=this.getX();var oldY=this.getY();draw2d.Node.prototype.setPosition.call(this,xPos,yPos);for(var i=0;i<this.children.getSize();i++){var child=this.children.get(i);child.setPosition(child.getX()+this.getX()-oldX,child.getY()+this.getY()-oldY);}};draw2d.CompartmentFigure.prototype.onDrag=function(){var oldX=this.getX();var oldY=this.getY();draw2d.Node.prototype.onDrag.call(this);for(var i=0;i<this.children.getSize();i++){var child=this.children.get(i);child.setPosition(child.getX()+this.getX()-oldX,child.getY()+this.getY()-oldY);}};