/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.LineStartResizeHandle=function(_2360){draw2d.Rectangle.call(this);this.setDimension(10,10);this.setBackgroundColor(new draw2d.Color(0,255,0));this.setWorkflow(_2360);this.setZOrder(10000);};draw2d.LineStartResizeHandle.prototype=new draw2d.Rectangle;draw2d.LineStartResizeHandle.prototype.type="LineStartResizeHandle";draw2d.LineStartResizeHandle.prototype.onDragend=function(){var line=this.workflow.currentSelection;if(line instanceof draw2d.Connection){var start=line.sourceAnchor.getLocation(line.targetAnchor.getReferencePoint());line.setStartPoint(start.x,start.y);this.getWorkflow().showLineResizeHandles(line);line.setRouter(line.oldRouter);}else{if(this.command==null){return;}var x1=line.getStartX();var y1=line.getStartY();var x2=line.getEndX();var y2=line.getEndY();this.command.setEndPoints(x1,y1,x2,y2);this.getWorkflow().getCommandStack().execute(this.command);this.command=null;}};draw2d.LineStartResizeHandle.prototype.onDragstart=function(x,y){if(!this.canDrag){return false;}var line=this.workflow.currentSelection;if(line instanceof draw2d.Connection){this.command=new draw2d.CommandReconnect(line);line.oldRouter=line.getRouter();line.setRouter(new draw2d.NullConnectionRouter());}else{var x1=line.getStartX();var y1=line.getStartY();var x2=line.getEndX();var y2=line.getEndY();this.command=new draw2d.CommandMoveLine(line,x1,y1,x2,y2);}return true;};draw2d.LineStartResizeHandle.prototype.onDrag=function(){var oldX=this.getX();var oldY=this.getY();draw2d.Rectangle.prototype.onDrag.call(this);var diffX=oldX-this.getX();var diffY=oldY-this.getY();var _2372=this.workflow.currentSelection.getStartPoint();var line=this.workflow.currentSelection;line.setStartPoint(_2372.x-diffX,_2372.y-diffY);line.isMoving=true;};draw2d.LineStartResizeHandle.prototype.onDrop=function(_2374){var line=this.workflow.currentSelection;line.isMoving=false;if(line instanceof draw2d.Connection){this.command.setNewPorts(_2374,line.getTarget());this.getWorkflow().getCommandStack().execute(this.command);}this.command=null;};draw2d.LineStartResizeHandle.prototype.onKeyDown=function(_2376,ctrl){if(this.workflow!=null){this.workflow.onKeyDown(_2376,ctrl);}};draw2d.LineStartResizeHandle.prototype.fireMoveEvent=function(){};