/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.ManhattanConnectionRouter=function(){this.MINDIST=20;};draw2d.ManhattanConnectionRouter.prototype=new draw2d.ConnectionRouter;draw2d.ManhattanConnectionRouter.prototype.type="ManhattanConnectionRouter";draw2d.ManhattanConnectionRouter.prototype.route=function(conn){var _2664=conn.getStartPoint();var _2665=this.getStartDirection(conn);var toPt=conn.getEndPoint();var toDir=this.getEndDirection(conn);this._route(conn,toPt,toDir,_2664,_2665);};draw2d.ManhattanConnectionRouter.prototype._route=function(conn,_2669,_266a,toPt,toDir){var TOL=0.1;var _266e=0.01;var UP=0;var RIGHT=1;var DOWN=2;var LEFT=3;var xDiff=_2669.x-toPt.x;var yDiff=_2669.y-toPt.y;var point;var dir;if(((xDiff*xDiff)<(_266e))&&((yDiff*yDiff)<(_266e))){conn.addPoint(new draw2d.Point(toPt.x,toPt.y));return;}if(_266a==LEFT){if((xDiff>0)&&((yDiff*yDiff)<TOL)&&(toDir==RIGHT)){point=toPt;dir=toDir;}else{if(xDiff<0){point=new draw2d.Point(_2669.x-this.MINDIST,_2669.y);}else{if(((yDiff>0)&&(toDir==DOWN))||((yDiff<0)&&(toDir==UP))){point=new draw2d.Point(toPt.x,_2669.y);}else{if(_266a==toDir){var pos=Math.min(_2669.x,toPt.x)-this.MINDIST;point=new draw2d.Point(pos,_2669.y);}else{point=new draw2d.Point(_2669.x-(xDiff/2),_2669.y);}}}if(yDiff>0){dir=UP;}else{dir=DOWN;}}}else{if(_266a==RIGHT){if((xDiff<0)&&((yDiff*yDiff)<TOL)&&(toDir==LEFT)){point=toPt;dir=toDir;}else{if(xDiff>0){point=new draw2d.Point(_2669.x+this.MINDIST,_2669.y);}else{if(((yDiff>0)&&(toDir==DOWN))||((yDiff<0)&&(toDir==UP))){point=new draw2d.Point(toPt.x,_2669.y);}else{if(_266a==toDir){var pos=Math.max(_2669.x,toPt.x)+this.MINDIST;point=new draw2d.Point(pos,_2669.y);}else{point=new draw2d.Point(_2669.x-(xDiff/2),_2669.y);}}}if(yDiff>0){dir=UP;}else{dir=DOWN;}}}else{if(_266a==DOWN){if(((xDiff*xDiff)<TOL)&&(yDiff<0)&&(toDir==UP)){point=toPt;dir=toDir;}else{if(yDiff>0){point=new draw2d.Point(_2669.x,_2669.y+this.MINDIST);}else{if(((xDiff>0)&&(toDir==RIGHT))||((xDiff<0)&&(toDir==LEFT))){point=new draw2d.Point(_2669.x,toPt.y);}else{if(_266a==toDir){var pos=Math.max(_2669.y,toPt.y)+this.MINDIST;point=new draw2d.Point(_2669.x,pos);}else{point=new draw2d.Point(_2669.x,_2669.y-(yDiff/2));}}}if(xDiff>0){dir=LEFT;}else{dir=RIGHT;}}}else{if(_266a==UP){if(((xDiff*xDiff)<TOL)&&(yDiff>0)&&(toDir==DOWN)){point=toPt;dir=toDir;}else{if(yDiff<0){point=new draw2d.Point(_2669.x,_2669.y-this.MINDIST);}else{if(((xDiff>0)&&(toDir==RIGHT))||((xDiff<0)&&(toDir==LEFT))){point=new draw2d.Point(_2669.x,toPt.y);}else{if(_266a==toDir){var pos=Math.min(_2669.y,toPt.y)-this.MINDIST;point=new draw2d.Point(_2669.x,pos);}else{point=new draw2d.Point(_2669.x,_2669.y-(yDiff/2));}}}if(xDiff>0){dir=LEFT;}else{dir=RIGHT;}}}}}}this._route(conn,point,dir,toPt,toDir);conn.addPoint(_2669);};