/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.PropertyWindow=function(){this.currentSelection=null;draw2d.Window.call(this,"Property Window");this.setDimension(200,100);};draw2d.PropertyWindow.prototype=new draw2d.Window;draw2d.PropertyWindow.prototype.type="PropertyWindow";draw2d.PropertyWindow.prototype.dispose=function(){draw2d.Window.prototype.dispose.call(this);};draw2d.PropertyWindow.prototype.createHTMLElement=function(){var item=draw2d.Window.prototype.createHTMLElement.call(this);item.appendChild(this.createLabel("Type:",15,25));item.appendChild(this.createLabel("X :",15,50));item.appendChild(this.createLabel("Y :",15,70));item.appendChild(this.createLabel("Width :",85,50));item.appendChild(this.createLabel("Height :",85,70));this.labelType=this.createLabel("",50,25);this.labelX=this.createLabel("",40,50);this.labelY=this.createLabel("",40,70);this.labelWidth=this.createLabel("",135,50);this.labelHeight=this.createLabel("",135,70);this.labelType.style.fontWeight="normal";this.labelX.style.fontWeight="normal";this.labelY.style.fontWeight="normal";this.labelWidth.style.fontWeight="normal";this.labelHeight.style.fontWeight="normal";item.appendChild(this.labelType);item.appendChild(this.labelX);item.appendChild(this.labelY);item.appendChild(this.labelWidth);item.appendChild(this.labelHeight);return item;};draw2d.PropertyWindow.prototype.onSelectionChanged=function(_268e){draw2d.Window.prototype.onSelectionChanged.call(this,_268e);if(this.currentSelection!=null){this.currentSelection.detachMoveListener(this);}this.currentSelection=_268e;if(_268e!=null&&_268e!=this){this.labelType.innerHTML=_268e.type;if(_268e.getX){this.labelX.innerHTML=_268e.getX();this.labelY.innerHTML=_268e.getY();this.labelWidth.innerHTML=_268e.getWidth();this.labelHeight.innerHTML=_268e.getHeight();this.currentSelection=_268e;this.currentSelection.attachMoveListener(this);}else{this.labelX.innerHTML="";this.labelY.innerHTML="";this.labelWidth.innerHTML="";this.labelHeight.innerHTML="";}}else{this.labelType.innerHTML="&lt;none&gt;";this.labelX.innerHTML="";this.labelY.innerHTML="";this.labelWidth.innerHTML="";this.labelHeight.innerHTML="";}};draw2d.PropertyWindow.prototype.getCurrentSelection=function(){return this.currentSelection;};draw2d.PropertyWindow.prototype.onOtherFigureMoved=function(_268f){if(_268f==this.currentSelection){this.onSelectionChanged(_268f);}};draw2d.PropertyWindow.prototype.createLabel=function(text,x,y){var l=document.createElement("div");l.style.position="absolute";l.style.left=x+"px";l.style.top=y+"px";l.style.font="normal 10px verdana";l.style.whiteSpace="nowrap";l.style.fontWeight="bold";l.innerHTML=text;return l;};