/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

shape.uml.Actor=function(name){VectorFigure.call(this);this.setName(name);this.setDimension(50,90);};shape.uml.Actor.prototype=new VectorFigure;shape.uml.Actor.prototype.type="shape.uml.Actor";shape.uml.Actor.prototype.setName=function(name){this.label.innerHTML=name;};shape.uml.Actor.prototype.setWorkflow=function(_1194){VectorFigure.prototype.setWorkflow.call(this,_1194);if(_1194!=null&&this.portRight==null){this.portRight=new Port();this.portRight.setWorkflow(_1194);this.addPort(this.portRight,this.width,this.height/2);this.portLeft=new Port();this.portLeft.setWorkflow(_1194);this.addPort(this.portLeft,0,this.height/2);}};shape.uml.Actor.prototype.createHTMLElement=function(){var item=Figure.prototype.createHTMLElement.call(this);this.label=document.createElement("div");this.label.style.width="100%";this.label.style.height="20px";this.label.style.position="absolute";this.label.style.textAlign="center";this.label.style.top="0px";this.label.style.left="0px";this.label.style.fontSize="8pt";return item;};shape.uml.Actor.prototype.setDimension=function(w,h){VectorFigure.prototype.setDimension.call(this,w,h);if(this.portRight!=null){this.portRight.setPosition(this.width,this.height/2);this.portLeft.setPosition(0,this.height/2);}};shape.uml.Actor.prototype.paint=function(){VectorFigure.prototype.paint.call(this);var _1198=this.getWidth()/2;var _1199=this.getWidth()/4;var _119a=this.getHeight()/2;var _119b=parseInt(this.label.style.height);var _119c=this.getWidth()*0.2;var _119d=this.getHeight()*0.1;this.graphics.drawOval(_1198-_119c/2,0,_119c,_119d);this.graphics.drawLine(_1198,_119d,_1198,_119a);this.graphics.drawLine(_1199,_119d*2,this.getWidth()-_1199,_119d*2);this.graphics.drawLine(_1198,_119a,_1199,this.getHeight()-_119b);this.graphics.drawLine(_1198,_119a,this.getWidth()-_1199,this.getHeight()-_119b);this.graphics.paint();this.label.style.top=(this.getHeight()-_119b)+"px";this.html.appendChild(this.label);};